CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (

id UUID DEFAULT uuid_generate_v4() PRIMARY KEY ,
name VARCHAR (25) NOT NULL,
age int NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
passcode VARCHAR(50) NOT NULL,
mobile VARCHAR(50) NOT NULL,
address VARCHAR(50) NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);